### ISSUE TITLE
PyAutoGUI was unable to import pyscreeze.

### ISSUE THREAD

**Issue by twohand0809** [Detergent13/tft-bot#126] opened 2023-07-03 07:44 UTC
![螢幕擷取畫面 2023-07-03 153816](https://github.com/Detergent13/tft-bot/assets/108621278/b57b6af0-f1db-43b1-9ac3-9d152b103f67)

**Comment by RomeoAlphaEkko** [comment] 2023-07-03 07:55
Hi, when did you download it?
Did it work before?

**Comment by twohand0809** [comment] 2023-07-03 07:57
> 

not used
download today

**Comment by RomeoAlphaEkko** [comment] 2023-07-03 17:44
could you check which version of python you are running?

**Comment by Shadds** [comment] 2023-07-23 17:27
hi, i have same problem. Python 3.8.3

**Comment by Detergent13** [comment] 2023-07-23 21:00
@Shadds does it work fine when you run in a fresh anaconda environment? (After installing the necessary things)

**Comment by sotha-sil-zen** [comment] 2023-07-30 12:48
In my case, this is caused by api issue of pyscreeze.

In its recent release, pyscreeze.grab was removed,. Import it would cause exception.

So I just remove it like

https://github.com/asweigart/pyautogui/blob/b4255d0be42c377154c7d92337d7f8515fc63234/pyautogui/__init__.py#L181C22-L181C22

in which,grab has been removed and down here.

https://github.com/asweigart/pyautogui/blob/b4255d0be42c377154c7d92337d7f8515fc63234/pyautogui/__init__.py#L233C5-L233C51.

So, if you are using an old version of PyAutoGUI, you may need to check the __init__.py of PyAutoGUI, especially the two lines where pyscreeze and its functions are imported.

By the way, nice work :)

**Comment by unkn0wnVII** [comment] 2023-08-09 09:14
1. unistall PyAutoGUI 0.9.50
2. unistall PyScreeze 0.1.29
3. install PyScreeze 0.1.28
4. install PyAutoGUI 0.9.50

**Comment by Detergent13** [comment] 2024-02-14 19:08
Fixed with #138

**Closed by Detergent13** 2024-02-14 19:08 UTC
